# Generated by Django 5.1.4 on 2024-12-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lead_management",
            "0002_lead_status_alter_lead_phone_alter_lead_source_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("completeed", "Completed"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salespipeline",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("completeed", "Completed"),
                    ("lost", "Lost"),
                ],
                default="Lead",
                max_length=50,
            ),
        ),
    ]
